2023-08-27 16:16:23.965 | ERROR    | translation_chain.translation:run:46 - An error occurred during translation: This model's maximum context length is 4097 tokens. However, your messages resulted in 16433 tokens. Please reduce the length of the messages.
2023-08-27 16:18:21.913 | ERROR    | translation_chain.translation:run:46 - An error occurred during translation: This model's maximum context length is 4097 tokens. However, your messages resulted in 16433 tokens. Please reduce the length of the messages.
2023-08-27 16:19:45.355 | ERROR    | translation_chain.translation:run:46 - An error occurred during translation: This model's maximum context length is 4097 tokens. However, your messages resulted in 16433 tokens. Please reduce the length of the messages.
2023-08-27 16:20:32.886 | ERROR    | translation_chain.translation:run:46 - An error occurred during translation: This model's maximum context length is 4097 tokens. However, your messages resulted in 16433 tokens. Please reduce the length of the messages.
2023-08-27 16:20:57.827 | ERROR    | translation_chain.translation:run:46 - An error occurred during translation: This model's maximum context length is 4097 tokens. However, your messages resulted in 16433 tokens. Please reduce the length of the messages.
2023-08-27 16:53:25.231 | ERROR    | translation_chain.translation:run:45 - An error occurred during translation: Error communicating with OpenAI: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2023-08-27 17:07:25.534 | ERROR    | translation_chain.translation:run:47 - An error occurred during translation: Error communicating with OpenAI: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2023-08-27 17:17:32.306 | ERROR    | translation_chain.translation:run:47 - An error occurred during translation: Error communicating with OpenAI: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2023-08-27 18:44:05.195 | ERROR    | translation_chain.translation:run:47 - An error occurred during translation: Error communicating with OpenAI: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
